<?php
$this->headLink()->appendStylesheet($this->basePath('jquery/jquery-ui.min.css'));
$this->headScript()->appendFile($this->basePath('jquery/jquery-ui.min.js'));
$this->headScript()->appendFile($this->basePath('js/annonce/datepicker.js'));
$title = 'Add Annonce';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('annonce/add', array(), true));
echo $this->bs3form($form);
?>