<?php
$title = 'Annonce user info';
$this->headTitle($title);

$userSessionContainer = new \Zend\Session\Container('user');
$userObj = $userSessionContainer->offsetGet('obj');
if ($userObj instanceof \Annonce\Model\User\User) : ?>
    <div class="row">
        <label class="col-sm-2 text-right">
            id
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getId(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            username
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getUsername(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            Lastname
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getLastname(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            Firstname
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getFirstname(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            Email
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getEmail(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            Telephone
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getTelephone(); ?>
        </div>
    </div>
    <div class="row">
        <label class="col-sm-2 text-right">
            Role
        </label>
        <div class="col-sm-10 table-bordered">
            <?php echo $userObj->getRoleName(); ?>
        </div>
    </div>

<?php endif; ?>
